{% set name = "simplekv" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8953a36cb3741ea821c9de1962b5313bf6fe1b927f6ced2a55266eb8ce2cd0f6

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - simplekv
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://simplekv.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple key-value store for binary data.
  dev_url: https://github.com/mbr/simplekv

extra:
  recipe-maintainers:
    - xhochy
